[package]
name = "embedded"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = { version = "0.8", features = ["defmt"] }
embedded-graphics-simulator = "0.7.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
tokio = {version = "1.0", features = ["full"] }
